name: Build
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest
    steps:
      - uses: taiga-family/ci/actions/setup/checkout@v1.84.0
      - uses: taiga-family/ci/actions/setup/variables@v1.84.0
      - uses: taiga-family/ci/actions/setup/node@v1.84.0
      - run: npx nx build

concurrency:
  group: build-${{ github.head_ref }}
  cancel-in-progress: true
