name: ⚙️ Build lib
on:
  pull_request:
  push:
    branches:
      - v1

jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest
    steps:
      - uses: taiga-family/ci/actions/setup/checkout@v1.65.3
      - uses: taiga-family/ci/actions/setup/variables@v1.65.3
      - uses: taiga-family/ci/actions/setup/node@v1.65.3
      - run: npx nx build

concurrency:
  group: build-${{ github.head_ref }}
  cancel-in-progress: true
