name: 🚀 Deploy / preview
on: pull_request

jobs:
  build_and_preview:
    name: Firebase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: taiga-family/ci/actions/setup/variables@30acd5f9c51f51e47ceb0662ff16199c3628e1bf # v1.126.0
      - uses: taiga-family/ci/actions/setup/node@30acd5f9c51f51e47ceb0662ff16199c3628e1bf # v1.126.0
      - run: npx nx build --base-href='/'
      - name: Debug output
        run: tree dist/apps/taiga-lumbermill/browser -P '*.html'
      - name: Deploy preview
        uses: FirebaseExtended/action-hosting-deploy@500ac625ca2dd40cbd15f7659af953801858032a # v0
        if: env.IS_OWNER_MODE == 'true'
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_TAIGA_LUMBERMILL_SA }}
          projectId: taiga-lumbermill-a3373
          expires: 1d

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
