name: 🤖 PR is ready to merge
on:
  pull_request_review:
    types: [submitted]

jobs:
  label-when-approved:
    name: Label when approved
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved'
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - uses: taiga-family/ci/actions/setup/variables@e9c5cd341c28d9aeb357b757df41cddcbb674b2d # v1.222.0
      - uses: taiga-family/ci/actions/auto/label-when-approved@e9c5cd341c28d9aeb357b757df41cddcbb674b2d # v1.222.0
        with:
          approvals: 1
          token: ${{ secrets.GITHUB_TOKEN }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
