name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: taiga-family/ci/actions/setup/variables@ad2e311a6700d8fc7efab79f8b8a2165888ff968 # v2.20.0
      - uses: taiga-family/ci/actions/setup/node@ad2e311a6700d8fc7efab79f8b8a2165888ff968 # v2.20.0
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Run Tests
        run: npx nx run-many --target test --all
      - uses: actions/upload-artifact@cf430e030ddbb5b0abf93d22962f4752f3646cd9 # v7.0.2
        with:
          name: coverage-${{ github.workflow }}-${{ github.run_id }}
          path: coverage

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
